version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - newman/newman-run:
          collection: ./collection.json 
          environment: dev_env.json 

workflows:
  example-workflow:
    jobs:
      - example-job
